name: "Repository Creation"
on:
  issues:
    types: [opened]

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue is labeled
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            if (!issue.labels.some(label => label.name === "create-repo")) {
              console.log("Issue is not labeled with 'create-repo'. Exiting...");
              return;
            }

      - name: Create GitHub Repository
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const repoName = issue.title.replace("New Repository Request: ", "").trim();
            const body = issue.body || "";

            let visibility = "public"; // Default visibility
            const match = body.match(/Repository Visibility:\s*(public|private)/i);
            if (match) {
              visibility = match[1].trim().toLowerCase();
            }

            console.log(`Creating repo: ${repoName} with visibility: ${visibility}`);

            // Use the correct API based on whether it's an org or personal account
            await github.rest.repos.createForAuthenticatedUser({
              name: repoName,
              private: visibility === "private"
            });

      - name: Close Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              state: "closed"
            });
